create or replace function public.emit_application_notification()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_recipient uuid; v_type text; v_title text; v_message text;
begin
 if new.to_status='SUBMITTED' then select landlord_profiles.user_id into v_recipient from public.applications join public.listings on listings.id=applications.listing_id join public.properties on properties.id=listings.property_id join public.landlord_profiles on landlord_profiles.id=properties.landlord_id where applications.id=new.application_id;v_type:='APPLICATION_SUBMITTED';v_title:='New rental application';v_message:='A tenant submitted a rental application.';
 elsif new.to_status='UNDER_REVIEW' then select tenant_profiles.user_id into v_recipient from public.applications join public.tenant_profiles on tenant_profiles.id=applications.tenant_id where applications.id=new.application_id;v_type:='APPLICATION_UNDER_REVIEW';v_title:='Your application is under review';v_message:='Your rental application is now under review.';
 elsif new.to_status='SHORTLISTED' then select tenant_profiles.user_id into v_recipient from public.applications join public.tenant_profiles on tenant_profiles.id=applications.tenant_id where applications.id=new.application_id;v_type:='APPLICATION_SHORTLISTED';v_title:='Your application was shortlisted';v_message:='Your rental application was shortlisted.';
 elsif new.to_status='REJECTED' then select tenant_profiles.user_id into v_recipient from public.applications join public.tenant_profiles on tenant_profiles.id=applications.tenant_id where applications.id=new.application_id;v_type:='APPLICATION_REJECTED';v_title:='Your application was not selected';v_message:='Your rental application was not selected.';
 elsif new.to_status='WITHDRAWN' then select landlord_profiles.user_id into v_recipient from public.applications join public.listings on listings.id=applications.listing_id join public.properties on properties.id=listings.property_id join public.landlord_profiles on landlord_profiles.id=properties.landlord_id where applications.id=new.application_id;v_type:='APPLICATION_WITHDRAWN';v_title:='Application withdrawn';v_message:='A tenant withdrew a rental application.';
 elsif new.to_status='ACCEPTED' then select tenant_profiles.user_id into v_recipient from public.applications join public.tenant_profiles on tenant_profiles.id=applications.tenant_id where applications.id=new.application_id;v_type:='APPLICATION_ACCEPTED';v_title:='Application accepted';v_message:='Your rental application was accepted.';
 else return new; end if;
 if v_recipient is not null then begin insert into public.notifications(user_id,type,title,message,entity_type,entity_id,source_event_key) values(v_recipient,v_type,v_title,v_message,'APPLICATION',new.application_id,'application_status_history:'||new.id::text);exception when unique_violation then null;end;end if;return new;
end; $$;
